/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.SQLException;

public class App {
  public static void main(String[] args) throws SQLException {
    Product product = new Product("Product 1", "Category 1", 10, 1000);
    ProductDao productDao = new ProductDao();
    productDao.addProduct(product);
  }
}
