/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.stage.Stage;

public class App extends Application {
  public static void main(String[] args) {
    launch();
  }

  @Override
  public void start(Stage primaryStage) throws Exception {
    ObservableList<ProduitView> produits =
        FXCollections.observableArrayList(new ProduitView("produit 1", "categorie 1", 0, 0));

    Scene scene = new Scene(initTableView(produits), 800, 600);
    produits.add(new ProduitView("produit 2", "categorie 2", 0, 0));
    primaryStage.setScene(scene);
    primaryStage.show();
  }

  public TableView<ProduitView> initTableView(ObservableList<ProduitView> produits) {
    TableView<ProduitView> tableView = new TableView<>(produits);

    TableColumn<ProduitView, String> nomCol = new TableColumn<>("Nom");
    nomCol.setCellValueFactory(p -> p.getValue().getNom());
    nomCol.prefWidthProperty().bind(tableView.widthProperty().multiply(0.25));

    TableColumn<ProduitView, String> categorieCol = new TableColumn<>("Catégorie");
    categorieCol.setCellValueFactory(p -> p.getValue().getCategorie());
    categorieCol.prefWidthProperty().bind(tableView.widthProperty().multiply(0.25));

    TableColumn<ProduitView, Number> prixCol = new TableColumn<>("Prix");
    prixCol.setCellValueFactory(p -> p.getValue().getPrix());
    prixCol.prefWidthProperty().bind(tableView.widthProperty().multiply(0.25));

    TableColumn<ProduitView, Number> quantiteCol = new TableColumn<>("Quantité");
    quantiteCol.setCellValueFactory(p -> p.getValue().getQuantite());
    quantiteCol.prefWidthProperty().bind(tableView.widthProperty().multiply(0.25));

    tableView.getColumns().addAll(List.of(nomCol, categorieCol, prixCol, quantiteCol));

    return tableView;
  }
}
