/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.RowConstraints;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
  public static void main(String[] args) {
    launch();
  }

  @Override
  public void start(Stage primaryStage) throws Exception {
    ObservableList<ProduitView> produits =
        FXCollections.observableArrayList(new ProduitView("produit 1", "categorie 1", 0, 0));

    TextField tfNom = new TextField();
    TextField tfCategorie = new TextField();
    TextField tfPrix = new TextField();
    TextField tfQuantite = new TextField();
    Button btnAjouterProduit = new Button("Ajouter produit");
    VBox vBox = new VBox(tfNom, tfCategorie, tfPrix, tfQuantite, btnAjouterProduit);
    TableView<ProduitView> tableView = initTableView(produits);

    GridPane gridPane = initGridPane();
    gridPane.add(tableView, 0, 0);
    gridPane.add(vBox, 1, 0);
    gridPane.setGridLinesVisible(false);

    Scene scene = new Scene(gridPane, 800, 600);
    produits.add(new ProduitView("produit 2", "categorie 2", 0, 0));
    primaryStage.setScene(scene);
    primaryStage.show();
  }

  public TableView<ProduitView> initTableView(ObservableList<ProduitView> produits) {
    TableView<ProduitView> tableView = new TableView<>(produits);

    TableColumn<ProduitView, String> nomCol = new TableColumn<>("Nom");
    nomCol.setCellValueFactory(p -> p.getValue().getNom());

    TableColumn<ProduitView, String> categorieCol = new TableColumn<>("Catégorie");
    categorieCol.setCellValueFactory(p -> p.getValue().getCategorie());

    TableColumn<ProduitView, Number> prixCol = new TableColumn<>("Prix");
    prixCol.setCellValueFactory(p -> p.getValue().getPrix());

    TableColumn<ProduitView, Number> quantiteCol = new TableColumn<>("Quantité");
    quantiteCol.setCellValueFactory(p -> p.getValue().getQuantite());

    tableView.getColumns().addAll(List.of(nomCol, categorieCol, prixCol, quantiteCol));
    tableView.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);

    return tableView;
  }

  public GridPane initGridPane() {
    GridPane pane = new GridPane(16, 0);
    ColumnConstraints tableColumnConstraints = new ColumnConstraints();
    ColumnConstraints formColumnConstraints = new ColumnConstraints();
    RowConstraints rowConstraints = new RowConstraints();

    tableColumnConstraints.setPercentWidth(70);
    formColumnConstraints.setPercentWidth(30);
    rowConstraints.setPercentHeight(100);

    pane.getColumnConstraints().addAll(tableColumnConstraints, formColumnConstraints);
    pane.getRowConstraints().add(rowConstraints);

    return pane;
  }
}
